### PR TITLE
added packages to be installed prior to rheas

### PR DESCRIPTION
**Pull request by oware**

### CODE REVIEW

**Comment by kandread** [comment]
hi @oware, were there any issues with psycopg2 and netcdf4? They're installed by buildout so there really is no need to install them system-wide. psycopg2 also needs to point to the postgresql installation that's local to rheas. I'm closing for now but I can reopen if you feel strongly about using a system postgresql (we'll need to refactor the code to use the /usr/bin/\* commands).

**Comment by oware** [comment]
ok, i understand, should have been an issue instead of pull request. Though, psycopg2 and netcdf were not installed by buildout, we had to install via apt-get.

**Comment by kandread** [comment]
That shouldn't happen. I tested the installation and didn't have that issue. What system did you try it on? Can you post the error message here?

**Comment by oware** [comment]
system is ubuntu 14.04. After running buildout, we used the system python console to load data into the database, the error was that pyscopg2 and netcdf were missing. will run more tests on a different server

**Comment by AdamJDuncan** [comment]
Try solely within the terminal

**Pull request closed without merging**
